version: '3'

services:
  rails: &app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3333:3000
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpack
    env_file:
      - .env
    volumes:
      - ..:/app:delegated
      - /app/log
      - /public/packs
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    tty: true
  webpack:
    <<: *app
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  db:
    image: mysql:8.0.26
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  bundle:
  node_modules:
  db-data:
